### ISSUE TITLE
MathLive demo is difficult to read in dark mode

### ISSUE THREAD

**Issue by zphyrj** [cortex-js/cortexjs.io#14]
Problem:
When my device's dark mode is on the MathLive demo at the bottom of the page https://cortexjs.io/mathlive/demo/ shows the text in a light gray color which makes it difficult to read.
<img width="793" alt="image" src="https://user-images.githubusercontent.com/46908127/161845463-20d9cbd5-8d31-4e5a-a51f-bc2f01ceae87.png">
Proposed Solution:
Within the css for `.result` on [line 96 of code-playground.ts](https://github.com/ui-js/code-playground/blob/0f459c278a74358cb4e4d09d5f32bde922dbfdd2/src/code-playground.ts#L96) add a `color: black;` to that style so that it becomes:
```diff
.result {
    width: calc(50% - .5em);
    margin-left: .5em;
+    color: black;
  }
```
I tried my fix using chrome devtools and it seemed to fix the issue:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46908127/161848140-083e872e-a316-4ce0-8ea7-f30bccc51835.png">

**Comment by arnog** [comment]
Thanks! I've deployed an update that should address this issue. Don't hesitate to report any other problems you might see. The paint on the Dark Mode is fresh!

**Comment by zphyrj** [comment]
Awesome, I love the demo even more in complete dark mode!
