### ISSUE TITLE
The text box on the demo page doesn't show LaTeX

### ISSUE THREAD

**Issue by andromeda951** [cortex-js/cortexjs.io#15]
After the April 05, 2022 update, on firefox version 99.0.1 (64-bit) macOS, the text box on the demo page doesn't show LaTeX.

**Comment by arnog** [comment]
Do you mean this page: https://cortexjs.io/mathlive/demo/ ?

I've tried it, but it seems to work for me. Could you include a screenshot of what you are seeing? Have you tried with another browser, and is it different?

**Comment by gunnarmein-ts** [comment]
On a plane right now, slow internet. Demo page. The LaTEX takes 5 second to appear after the formula appears on Chrome. On Safari, significantly longer. Perhaps that is what the OP is observing.

**Comment by arnog** [comment]
Oh, I see. The library is somehow loaded 6 times. That could contribute to the problem. I'll look into it.

**Comment by arnog** [comment]
OK, when loading the fonts (and sounds), the origin of the library needs to be resolved to determine the relative location of those files. This was done with a http `GET` for each font, while it only needs to be done once, and with a `HEAD`, to avoid having to re-download the entire library.

**Comment by arnog** [comment]
Fixed in MathLive 3fb439447ff15a6f606d7d4c5168dc90ab8dcea1

**Comment by arnog** [comment]
Deployed to cortextjs.io
