### ISSUE TITLE
Typos in Interacting with a Mathfield

### ISSUE THREAD

**Issue by hexaron** [cortex-js/cortexjs.io#16]
Hi guys,

there seem to be two typos in

https://github.com/cortex-js/cortexjs.io/blob/1f9833fad55cee3633c7f3674c2535a3f6d641ae/src/_pages/mathlive-guide-interacting.md?plain=1#L280-L284

For one, the `.` at the end of the line is incorrect syntax, second, the variable `mg` is not defined.
I believe the correct code should be:

```js
mf.setOptions({onExport: (mg, latex, range) => 
  "`" + mg.getValue(range, 'ascii-math') + "`"
});
```

This also applies to the above two code snippets.

**Comment by arnog** [comment]
Good catch! Thanks for reporting it. Fixed now.
