### ISSUE TITLE
Basic use of simplify

### ISSUE THREAD

**Issue by smaxx73** [cortex-js/cortexjs.io#17]
Hi, here is my code : 
```
const engine = new ComputeEngine()
expression = '2+\\frac{2+x}{2}'
expression2 = engine.parse(expression).simplify().latex
```

After printing expression = expression2 the result is : 
![image](https://user-images.githubusercontent.com/17359037/172799752-1ca08181-6619-4684-ae7e-7794120fa93d.png)

What is wrong ? Have I missed some basic stuff ?

**Comment by arnog** [comment]
This is fixed in the main branch of the compute engine.
