### ISSUE TITLE
MathJSON confused

### ISSUE THREAD

**Issue by tqtrungse** [cortex-js/cortexjs.io#18]
Hi,

I have used [demo](https://cortexjs.io/mathlive/demo/) with expression: x = abs(-10). 
I received the math JSON expression `[
  "Equal", 
  "x", 
  ["Multiply", "abs", ["Delimiter", -10]]
]`

What is the "Delimiter"? 
Why do you add multiplication? 
The "ceil" function has the same issue as the "abs", but the "round" and "floor" function is good.  
Do I miss something?

Thanks

**Comment by arnog** [comment]
There wasn't a definition for the `abs()` (or `ceil()`) functions. The absolute value is usually indicated with vertical bars `|-10|`.
The  definitions have now been added in the main branch of the compute engine.
