### ISSUE TITLE
Legacy React Doc link in "Using MathLive with React" Section

### ISSUE THREAD

**Issue by noobyogi0010** [cortex-js/cortexjs.io#29]
When you are checking out MathLive and navigate to the "Using MathLive with React" section. At the bottom of the page, there is a link to React docs with the text "Learn more about React and Web Components" which links to legacy react docs for Web Component.
I would love to update it to the latest react documentation if no one has any objections.
Thanks. 
PS: Adding an ss for reference.

![image](https://user-images.githubusercontent.com/55592987/227795599-955ac6f4-6806-4d35-bbef-e568797857e2.png)

**Comment by arnog** [comment]
What link do you propose to update it to?

**Comment by noobyogi0010** [comment]
The Quick Start page of React learn: https://react.dev/learn

**Comment by arnog** [comment]
That looks like a good general purpose introduction to using React, but I'm looking for a page that discuss specifically how to use web components like `<math-field>` along with React. The old documentation page includes some useful information that I haven't seen elsewhere.

**Comment by noobyogi0010** [comment]
You have a point.
How about this one: https://react.dev/learn/your-first-component ?
It talks extensively about what components are and how you can use them.

**Comment by arnog** [comment]
Ah, I see the confusion. That page is about **React** components. I'm looking for a page that discusses using **web* components inside React. 

Web components and React components are two completely different things, but unfortunately their name are confusing, and sometimes (as in the page you cite), "component" is used without clarifying if talking about web components or React components...

**Comment by arnog** [comment]
The documentation has been updated.
