### ISSUE TITLE
Custom layout switcher label not clickable

### ISSUE THREAD

**Issue by damaldon8011** [cortex-js/cortexjs.io#30]
Hi, i have created a custom layout, defined label, tooltip and rows but when the virtual keyboard is displayed, the switcher label is not being clickable, i got a forced solution displaying this custom layout as the first pos layout between default layouts like "greek", "alphabetic" etc but after switch on another layout i cant to do click at custom layout again.

Thanks!

**Comment by arnog** [comment]
This is a MathLive issue, fixed in https://github.com/arnog/mathlive 78ba96e817a651b1fcc1597e5a3a09f7bf5b1d4d
