### ISSUE TITLE
CortexJS onine tool: how to write on several lines?

### ISSUE THREAD

**Issue by Ultome** [cortex-js/cortexjs.io#32]
I find CortexJS really nice and I would like to use it more, but the problem is I can't find a way to write a new line... When I'm thinking through a problem, I kind of need to see the previous steps, it's a problem if I have to erase what I've done before everytime I need to write a new line...

Is there a way? And if there is not, would you implement it?

**Comment by arnog** [comment]
This is an upcoming feature in MathLive.

**Comment by sixiann** [comment]
Hi!! any updates on this feature? allowing text to wrap around to new lines

**Comment by arnog** [comment]
You can now add new lines in a mathfield by pressing alt/option+return.
