### ISSUE TITLE
not possible to define separate buttons in html without mathlive's built-in keyboard buttons

### ISSUE THREAD

**Issue by amanborka** [cortex-js/cortexjs.io#35]
Is there a function to introduce several buttons in HTML and click on them to enter a mathematical expression without using the mathlive keyboard?

**Comment by arnog** [comment]
Sure, you would do something like:

```html
<math-field id="mf"></math-field>
<button onclick="document.getElementById('mf').insert('\\pi')">Pi</button>
```

**Comment by amanborka** [comment]
> Sure, you would do something like:
> 
> ```
> <math-field id="mf"></math-field>
> <button onclick="document.getElementById('mf').insert('\\pi')">Pi</button>
> ```

Thank you very much, my problem is solved
