### ISSUE TITLE
programicaly insert divide '/' not working 

### ISSUE THREAD

**Issue by amanborka** [cortex-js/cortexjs.io#36]
inserting divide symbol / doesn't work programmatically like \sqrt{} works

`<button on:click={()=>m.insert('/')}>insert divide</button>`

**Comment by arnog** [comment]
I think you're looking for `m.insert('\\frac{}{}')`

**Comment by amanborka** [comment]
> I think you're looking for `m.insert('\\frac{}{}')`

this is not working for me

**Comment by arnog** [comment]
I'm sorry but there isn't enough information to resolve this issue. Could you describe what you did and what happens? Could you share the code you are using?

**Comment by amanborka** [comment]
> I'm sorry but there isn't enough information to resolve this issue. Could you describe what you did and what happens? Could you share the code you are using?

I want to enter this phrase that is in the image by clicking :

![MMMM](https://github.com/cortex-js/cortexjs.io/assets/127776937/4450d2c1-b9bf-4f1f-ae4b-f12e193bfa60)

**Comment by arnog** [comment]
When reporting an issue, please include code demonstrating the problem. I still don't know what your code does, nor what happens. "Not working" is a very vague description.

I'm going to make guesses, but without more information this is very difficult. Did you try `mf.insert("\\frac{#?}{#?}")` or `mf.insert("\\frac{1}{2}")`?

**Comment by amanborka** [comment]
> \\frac{#?}{#?}

It worked, thank you
I'm very sorry, I'm new to writing here, so please accept my apologies

Thank you once again
