### ISSUE TITLE
Math live demo on iOS dark screen 

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/cortexjs.io#38]
When in dark screen mode and viewing the main page demo, you cannot see the text in a  selected area. 

![IMG_0921](https://github.com/cortex-js/cortexjs.io/assets/39233783/48f70dee-9488-46d7-8062-7fb36c1d9ea4)

Apologies in advance as it looks like I opened this on the wrong repo.

**Comment by arnog** [comment]
Fixed now.
