### ISSUE TITLE
Broken link in Canonical Form guide

### ISSUE THREAD

**Issue by nathancarter** [cortex-js/cortexjs.io#44]
On [this page](https://cortexjs.io/compute-engine/guides/canonical-form) there is a link to docs for `ce.jsonSerializationOptions`, but it is a broken link [leading here](https://cortexjs.io/docs/guide-expressions#unboxing) when it should actually lead [to this documentation instead](https://cortexjs.io/docs/compute-engine/#(ComputeEngine%3Aclass).(jsonSerializationOptions%3Ainstance)), I think.  I would fix it with a small pull request, but I'm not sure the syntax for the doc system.

**Comment by arnog** [comment]
Thanks for reporting the issue. Fixed.
