### ISSUE TITLE
Mathlive Docs update: Controling the Menu Visibility should mention that menuItems = [] should be done after "mount" event.

### ISSUE THREAD

**Issue by screambeard** [cortex-js/cortexjs.io#45]
The new contextMenu looks awesome! But for inline editors this might be too much.

The documentation now states that you can disable the contextMenu by doing: `mf.menuItems = [];`. However, this needs to be done after the mathFieldElement is "mounted", otherwise the menuItems property will be overwritten again with the default list of menuItems.

I propose to add this in the documentation where it is explained how to disable the contextMenu: https://cortexjs.io/mathlive/guides/menu/

**Comment by arnog** [comment]
Ah, good point. This should have worked. It will be fixed in the next release of MathLive.
