### ISSUE TITLE
z-index on the virtual keyboard

### ISSUE THREAD

**Issue by GeO95** [cortex-js/cortexjs.io#9]
I get an issue when I have the virtual keyboard which pops up over a bootstrap accordion.
The zindex of the different items are not correct and the accordion comes over the keyboard.
I would need to change the zindex attribute of the keyboard but I can't find it...
Can you point me to the right direction please?

**Comment by arnog** [comment]
You can control the z-index of the virtual keyboard by setting the `--keyboard-zindex` CSS variable, for example on the body of your document:

```css
body {
    --keyboard-zindex: 1000;
}
```
